### ISSUE TITLE
Shadows to tiles casting issues

### ISSUE THREAD

**Issue by Bohicatv** [kaczy93/centredsharp#31]
Coordinates : 4261, 661
![image](https://github.com/user-attachments/assets/15592188-5048-4407-8d04-ff4b1ec82427)

**Comment by kaczy93** [comment]
I must have missed some edge case when tweaking terrain shadows recently, will take a look

**Comment by kaczy93** [comment]
Should be fixed in 0.6.2.3

**Comment by Bohicatv** [comment]
fixed
